spring.application.name=Error

spring.datasource.url=jdbc:mysql://localhost:3306/error
spring.datasource.username=sasm
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
file.upload-dir=uploads/
